## examples/handle_exception.av

try {
  throw "an exception";
} catch(e) {
  ## print stack trace
  pst(e);
} finally {
  p("finally");
}
